INSTALL script updated

diff --git a/INSTALL b/INSTALL
--- a/INSTALL
+++ b/INSTALL
@@ -7,10 +7,10 @@ f90_libs='-lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lmkl_def -lpthread'
 f90_opt='-fast'
 #f90_opt='-check all'
 
-f2py_exe='0'
-if [ $f2py_exe -eq '0' ]; then which f2py > /dev/null 2> /dev/null ; if [ $? -eq 0 ]; then f2py_exe=f2py; fi; fi
-if [ $f2py_exe -eq '0' ]; then which f2py2 > /dev/null 2> /dev/null; if [ $? -eq 0 ]; then f2py_exe=f2py2; fi; fi
-if [ $f2py_exe -eq '0' ]; then echo "!Error: Install f2py support."; exit; fi
+f2py_exe='none'
+if [ $f2py_exe = 'none' ]; then which f2py > /dev/null 2> /dev/null ; if [ $? -eq 0 ]; then f2py_exe=f2py; fi; fi
+if [ $f2py_exe = 'none' ]; then which f2py2 > /dev/null 2> /dev/null; if [ $? -eq 0 ]; then f2py_exe=f2py2; fi; fi
+if [ $f2py_exe = 'none' ]; then echo "!Error: Install f2py support."; exit; fi
 
 
 if [ ! -d xdrfiles ]; then
